export class TokenError extends Error {
  constructor(
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'TokenError';
  }
}

export const TokenErrorCode = {
  MINT_WITHOUT_POT: 'TOKEN_MINT_WITHOUT_POT',
  DOUBLE_MINT: 'TOKEN_DOUBLE_MINT',
  INVALID_AMOUNT: 'TOKEN_INVALID_AMOUNT',
  INSUFFICIENT_BALANCE: 'TOKEN_INSUFFICIENT_BALANCE',
  TRANSFER_WITHOUT_POT: 'TOKEN_TRANSFER_WITHOUT_POT',
  REVALUATION_WITHOUT_POT: 'TOKEN_REVALUATION_WITHOUT_POT',
  INVALID_HOLDER: 'TOKEN_INVALID_HOLDER',
  INVALID_PROCESS: 'TOKEN_INVALID_PROCESS',
  ZERO_SUPPLY_REVAL: 'TOKEN_ZERO_SUPPLY_REVAL',
  POT_HEIGHT_REQUIRED: 'TOKEN_POT_HEIGHT_REQUIRED',
  PROCESS_CLOSE_EXTINGUISH: 'TOKEN_PROCESS_CLOSE_EXTINGUISH',
} as const;
